version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 15
      package-average: 10
    dupl:
      threshold: 100
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    misspell:
      locale: US
    nilnil:
      checked-types:
        - ptr
        - func
        - iface
        - map
        - chan
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: indent-error-flow
        - name: if-return
        - name: superfluous-else
        - name: unused-parameter
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: snake
          mapstructure: kebab
          xml: camel
          yaml: snake
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - dupl
          - funlen
          - gocognit
          - lll
          - mnd
        path: _test\.go
      - linters:
          - gochecknoinits
        path: cmd/
      - linters:
          - mnd
        path: pkg/version/
      - path: (.+)\.go$
        text: Line contains TODO/BUG/FIXME
      - path: (.+)\.go$
        text: 'Magic number: [0-9]+'
      - path: (.+)\.go$
        text: don't use underscores in Go names
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cychiang/xp-provider-gen)
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/cychiang/xp-provider-gen
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
