/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v2

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/afero"
	"github.com/spf13/cobra"
	"sigs.k8s.io/kubebuilder/v4/pkg/config"
	"sigs.k8s.io/kubebuilder/v4/pkg/config/store"
	"sigs.k8s.io/kubebuilder/v4/pkg/config/store/yaml"
	"sigs.k8s.io/kubebuilder/v4/pkg/machinery"

	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/core"
	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/templates/engine"
	"github.com/cychiang/xp-provider-gen/pkg/version"
	"github.com/cychiang/xp-provider-gen/pkg/versions"
)

// NewUpdateCommand returns the `update` command, registered on the CLI via
// cli.WithExtraCommands (kubebuilder's plugin interface has no update hook).
func NewUpdateCommand() *cobra.Command {
	var adopt bool
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Refresh tool-owned core files of an existing provider",
		Long: `Regenerate the tool-owned core of an existing Crossplane provider — registration,
controller wiring (setup.go), main.go, config, and framework dependency versions —
to the current generator, without touching your business logic.

Tool-owned files carry a "// Code generated by xp-provider-gen. DO NOT EDIT." header
and are overwritten; files without it (controller.go, *_types.go, crossplane.yaml) are
left alone. go.mod itself is never overwritten — only its framework dependency versions
are bumped via 'go get', so your own requires are preserved.

The working tree must be clean; the result is left uncommitted so you can review it with
'git diff' before committing. If a step fails midway, run 'git reset --hard' to revert.

Use --adopt once on a provider generated before the ownership contract existed: it stamps
provenance and writes the header onto recognized tool-owned files so plain 'update' works.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			run := runUpdate
			if adopt {
				run = runAdopt
			}
			if err := run(context.Background()); err != nil {
				return fmt.Errorf("%w\n  changes are uncommitted; run 'git reset --hard' to revert", err)
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&adopt, "adopt", false,
		"retrofit an existing provider: stamp provenance and add the generated header to "+
			"tool-owned files, then exit (run 'update' afterward to refresh them)")
	return cmd
}

// provenance records, in PROJECT, the generator version that last touched the project.
type provenance struct {
	Version string `json:"version"`
}

func runAdopt(ctx context.Context) error {
	disk := afero.NewOsFs()

	if err := requireCleanTree(ctx); err != nil {
		return err
	}

	store := yaml.New(machinery.Filesystem{FS: disk})
	if err := store.Load(); err != nil {
		return fmt.Errorf("not a provider project (cannot load PROJECT): %w", err)
	}
	cfg := store.Config()

	mem := afero.NewMemMapFs()
	if err := renderToMemFS(cfg, machinery.Filesystem{FS: mem}); err != nil {
		return fmt.Errorf("rendering tool-owned files: %w", err)
	}

	adopted, err := adoptHeaders(mem, disk)
	if err != nil {
		return fmt.Errorf("adopting tool-owned files: %w", err)
	}
	if err := stampProvenance(store); err != nil {
		return fmt.Errorf("stamping provenance: %w", err)
	}

	fmt.Printf("Adopted %d tool-owned file(s) and stamped generator version %s in PROJECT.\n",
		len(adopted), version.Get().Version)
	fmt.Println("Review with 'git diff', commit, then run 'xp-provider-gen update' to refresh them.")
	return nil
}

// adoptHeaders adds the generated header to on-disk files that the templates own
// (identified by the header in their rendered output) but that predate the
// ownership contract. User-owned files are left untouched.
func adoptHeaders(src, dst afero.Fs) ([]string, error) {
	var adopted []string
	err := afero.Walk(src, ".", func(path string, info fs.FileInfo, walkErr error) error {
		if walkErr != nil || info.IsDir() {
			return walkErr
		}
		rel, ok, err := adoptFile(src, dst, path)
		if err != nil {
			return err
		}
		if ok {
			adopted = append(adopted, rel)
		}
		return nil
	})
	return adopted, err
}

// adoptFile adds the header to one on-disk file if the matching rendered file is
// tool-owned and the on-disk file exists without it. Returns whether it adopted.
func adoptFile(src, dst afero.Fs, srcPath string) (string, bool, error) {
	rendered, err := afero.ReadFile(src, srcPath)
	if err != nil {
		return "", false, err
	}
	if !core.IsToolOwned(rendered) {
		return "", false, nil // user-owned template — never adopt
	}
	rel := strings.TrimPrefix(filepath.ToSlash(srcPath), "/")
	exists, err := afero.Exists(dst, rel)
	if err != nil {
		return "", false, err
	}
	if !exists {
		return "", false, nil // absent on disk — a later `update` will seed it
	}
	existing, err := afero.ReadFile(dst, rel)
	if err != nil {
		return "", false, err
	}
	if core.IsToolOwned(existing) {
		return "", false, nil // already carries the header
	}
	if err := afero.WriteFile(dst, rel, insertGeneratedHeader(existing), 0o644); err != nil {
		return "", false, err
	}
	return rel, true, nil
}

// insertGeneratedHeader places the header just before the package clause, where
// IsToolOwned looks. It is a no-op if the header is already present.
func insertGeneratedHeader(content []byte) []byte {
	if core.IsToolOwned(content) {
		return content
	}
	s := string(content)
	header := core.GeneratedHeader + "\n\n"
	if i := strings.Index(s, "\npackage "); i >= 0 {
		return []byte(s[:i+1] + header + s[i+1:])
	}
	return []byte(header + s)
}

// stampProvenance records the current generator version in PROJECT and saves it.
func stampProvenance(store store.Store) error {
	if err := store.Config().EncodePluginConfig(pluginName, provenance{Version: version.Get().Version}); err != nil {
		return fmt.Errorf("encoding provenance: %w", err)
	}
	return store.Save()
}

func runUpdate(ctx context.Context) error {
	disk := afero.NewOsFs()

	if err := requireCleanTree(ctx); err != nil {
		return err
	}

	store := yaml.New(machinery.Filesystem{FS: disk})
	if err := store.Load(); err != nil {
		return fmt.Errorf("not a provider project (cannot load PROJECT): %w", err)
	}
	cfg := store.Config()

	mem := afero.NewMemMapFs()
	if err := renderToMemFS(cfg, machinery.Filesystem{FS: mem}); err != nil {
		return fmt.Errorf("rendering tool-owned files: %w", err)
	}

	result, err := reconcile(mem, disk)
	if err != nil {
		return fmt.Errorf("reconciling generated files: %w", err)
	}
	result.print()

	if err := applyDependencies(ctx); err != nil {
		return err
	}

	fmt.Println("Finalizing (go mod tidy, make generate, make reviewable)...")
	for _, step := range [][]string{
		{"go", "mod", "tidy"},
		{"make", "generate"},
		{"make", "reviewable"},
	} {
		if err := runVisible(ctx, step[0], step[1:]...); err != nil {
			return fmt.Errorf("%s failed: %w", strings.Join(step, " "), err)
		}
	}

	if err := stampProvenance(store); err != nil {
		return fmt.Errorf("stamping provenance: %w", err)
	}

	fmt.Println("\nUpdate complete. Review the changes with 'git diff' and commit when ready.")
	return nil
}

// requireCleanTree aborts unless the working tree has no uncommitted changes, so
// the update is reviewable as a diff and no user edits are silently overwritten.
func requireCleanTree(ctx context.Context) error {
	out, err := core.NewCommandRunner("").RunWithOutput(ctx, "git", "status", "--porcelain")
	if err != nil {
		return fmt.Errorf("checking working tree (is this a git repository?): %w", err)
	}
	if strings.TrimSpace(out) != "" {
		return fmt.Errorf("working tree is not clean; commit or stash your changes first so " +
			"the update can be reviewed as a diff")
	}
	return nil
}

// renderToMemFS renders the full template set (init + static + register generators,
// plus each resource's API templates) into the given in-memory filesystem.
func renderToMemFS(cfg config.Config, memFS machinery.Filesystem) error {
	factory := engine.NewFactory(cfg)

	resources, err := cfg.GetResources()
	if err != nil {
		return fmt.Errorf("reading project resources: %w", err)
	}

	initTemplates, err := factory.GetInitTemplates()
	if err != nil {
		return fmt.Errorf("init templates: %w", err)
	}
	staticTemplates, err := factory.GetStaticTemplates()
	if err != nil {
		return fmt.Errorf("static templates: %w", err)
	}

	base := machinery.NewScaffold(memFS,
		machinery.WithConfig(cfg),
		machinery.WithBoilerplate(engine.DefaultBoilerplate()),
	)
	builders := append(engine.AsBuilders(initTemplates), engine.AsBuilders(staticTemplates)...)
	builders = append(builders, engine.RegisterGenerators(cfg, resources)...)
	if err := base.Execute(builders...); err != nil {
		return fmt.Errorf("rendering base templates: %w", err)
	}

	for _, res := range resources {
		apiTemplates, err := factory.GetAPITemplates(engine.WithForce(true), engine.WithResource(&res))
		if err != nil {
			return fmt.Errorf("api templates for %s: %w", res.Kind, err)
		}
		apiScaffold := machinery.NewScaffold(memFS,
			machinery.WithConfig(cfg),
			machinery.WithBoilerplate(engine.DefaultBoilerplate()),
			machinery.WithResource(&res),
		)
		if err := apiScaffold.Execute(engine.AsBuilders(apiTemplates)...); err != nil {
			return fmt.Errorf("rendering api templates for %s: %w", res.Kind, err)
		}
	}
	return nil
}

// reconcile copies every rendered file from src onto dst through the ownership
// gate: tool-owned (headered) files are overwritten, new files seeded, and
// user-owned (headerless) files left untouched.
func reconcile(src, dst afero.Fs) (reconcileResult, error) {
	var result reconcileResult
	err := afero.Walk(src, ".", func(path string, info fs.FileInfo, walkErr error) error {
		if walkErr != nil || info.IsDir() {
			return walkErr
		}
		rel := strings.TrimPrefix(filepath.ToSlash(path), "/")
		decision, err := applyFile(src, dst, path, rel)
		if err != nil {
			return err
		}
		result.record(decision, rel)
		return nil
	})
	return result, err
}

// applyFile reconciles one rendered file onto dst per the ownership gate.
func applyFile(src, dst afero.Fs, srcPath, rel string) (core.WriteDecision, error) {
	exists, err := afero.Exists(dst, rel)
	if err != nil {
		return core.Skip, err
	}
	var existing []byte
	if exists {
		if existing, err = afero.ReadFile(dst, rel); err != nil {
			return core.Skip, err
		}
	}

	decision := core.DecideWrite(exists, existing)
	if decision == core.Skip {
		return decision, nil
	}

	newContent, err := afero.ReadFile(src, srcPath)
	if err != nil {
		return decision, err
	}
	if err := dst.MkdirAll(filepath.Dir(rel), 0o755); err != nil {
		return decision, err
	}
	return decision, afero.WriteFile(dst, rel, newContent, 0o644)
}

type reconcileResult struct {
	overwritten []string
	seeded      []string
	skipped     []string
}

func (r *reconcileResult) record(decision core.WriteDecision, rel string) {
	switch decision {
	case core.Skip:
		r.skipped = append(r.skipped, rel)
	case core.Seed:
		r.seeded = append(r.seeded, rel)
	case core.Overwrite:
		r.overwritten = append(r.overwritten, rel)
	}
}

func (r reconcileResult) print() {
	fmt.Printf("Refreshed %d tool-owned file(s), added %d, left %d user-owned file(s) untouched.\n",
		len(r.overwritten), len(r.seeded), len(r.skipped))
}

// applyDependencies bumps the framework dependency versions from the manifest via
// `go get`, leaving the rest of go.mod (the user's own requires) alone.
func applyDependencies(ctx context.Context) error {
	deps, err := versions.GoModDependencies()
	if err != nil {
		return fmt.Errorf("loading dependency manifest: %w", err)
	}
	fmt.Printf("Applying %d framework dependency version(s)...\n", len(deps))
	for _, d := range deps {
		if err := runVisible(ctx, "go", "get", d.Module+"@"+d.Version); err != nil {
			return fmt.Errorf("go get %s@%s: %w", d.Module, d.Version, err)
		}
	}
	return nil
}

// runVisible runs a command with stdout/stderr connected so the user sees progress.
// The name and args are always fixed tool commands (go, make) or dependency
// coordinates from the embedded, repo-controlled manifest — never user input.
func runVisible(ctx context.Context, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...) // #nosec G204 -- see doc comment
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
