/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// The update command's own file: the cobra command, the prepare/run
// orchestration shared with adopt, and the project-loading and
// dependency-bumping helpers only update itself uses. The command's other
// responsibilities live in reconcile.go (the ownership-gated copy), adopt.go
// (--adopt) and tfversion.go (--terraform-provider-version).
package v2

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/afero"
	"github.com/spf13/cobra"
	"sigs.k8s.io/kubebuilder/v4/pkg/config"
	"sigs.k8s.io/kubebuilder/v4/pkg/config/store"
	"sigs.k8s.io/kubebuilder/v4/pkg/config/store/yaml"
	"sigs.k8s.io/kubebuilder/v4/pkg/machinery"

	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/automation"
	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/core"
	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/templates/engine"
	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/validation"
	"github.com/cychiang/xp-provider-gen/pkg/version"
)

// NewUpdateCommand returns the `update` command, registered on the CLI via
// cli.WithExtraCommands (kubebuilder's plugin interface has no update hook).
func NewUpdateCommand() *cobra.Command {
	var adopt bool
	var terraformProviderVersion string
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Refresh tool-owned core files of an existing provider",
		Long: `Regenerate the tool-owned core of an existing Crossplane provider — registration,
controller wiring (wiring.go), main.go, config, and framework dependency versions —
to the current generator, without touching your business logic.

Tool-owned files carry a "// Code generated by xp-provider-gen. DO NOT EDIT." header
and are overwritten; files without it (external.go, client.go, options.go, *_types.go,
crossplane.yaml) are left alone. go.mod itself is never overwritten — only its framework
dependency versions are bumped via 'go get', so your own requires are preserved.

On an upjet provider it never recreates a missing user-owned file — some need init-time
Terraform settings PROJECT does not keep, so it recreates none — and lists the ones it
skipped instead. Plain 'update' does not change the wrapped Terraform provider's version;
that lives in your Makefile — use --terraform-provider-version to bump it.

The working tree must be clean; the result is left uncommitted so you can review it with
'git diff' before committing. If a step fails midway, the error names exactly how to revert.

Use --adopt once on a provider generated before the ownership contract existed: it stamps
provenance and writes the header onto recognized tool-owned files so plain 'update' works.

Use --terraform-provider-version on an upjet provider to bump the wrapped Terraform
provider: it rewrites the version in your Makefile, then runs the rest of update as usual —
there is no way to bump only the version, since the generator refresh and framework
dependency bump ride along in the same diff.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			if adopt {
				return runAdopt(context.Background())
			}
			if terraformProviderVersion != "" {
				if err := checkTerraformVersionFlag(terraformProviderVersion); err != nil {
					return err
				}
			}
			return runUpdate(context.Background(), terraformProviderVersion)
		},
	}
	cmd.Flags().BoolVar(&adopt, "adopt", false,
		"retrofit an existing provider: stamp provenance and add the generated header to "+
			"tool-owned files, then exit (run 'update' afterward to refresh them)")
	cmd.Flags().StringVar(&terraformProviderVersion, "terraform-provider-version", "",
		"bump the wrapped Terraform provider to this version (upjet only): rewrites the Makefile, "+
			"then runs the rest of update as usual, including a fresh 'make generate'")
	cmd.MarkFlagsMutuallyExclusive("adopt", "terraform-provider-version")
	return cmd
}

// prepare enforces the clean-tree precondition, loads and validates the project, and
// renders the current template set of its flavor into an in-memory FS. Both update
// and adopt start here; it also returns the project's plugin block so later steps
// choose the same flavor's sets.
func prepare(ctx context.Context) (store.Store, afero.Fs, projectMeta, error) {
	if err := requireCleanTree(ctx); err != nil {
		return nil, nil, projectMeta{}, err
	}
	st, err := loadProjectStore()
	if err != nil {
		return nil, nil, projectMeta{}, err
	}
	meta, err := validateProject(st.Config())
	if err != nil {
		return nil, nil, projectMeta{}, err
	}
	mem := afero.NewMemMapFs()
	if err := renderToMemFS(st.Config(), meta, machinery.Filesystem{FS: mem}); err != nil {
		return nil, nil, projectMeta{}, fmt.Errorf("rendering tool-owned files: %w", err)
	}
	return st, mem, meta, nil
}

// stampProvenance records the current generator version in PROJECT and saves it.
func stampProvenance(st store.Store) error {
	if err := saveProjectMeta(st.Config(), func(m *projectMeta) {
		m.Version = version.Get().Version
	}); err != nil {
		return fmt.Errorf("encoding provenance: %w", err)
	}
	return st.Save()
}

func runUpdate(ctx context.Context, terraformProviderVersion string) error {
	st, mem, meta, err := prepare(ctx)
	if err != nil {
		return fmt.Errorf("%w\n  no changes were made; nothing to revert", err)
	}
	if err := checkNotDowngrade(meta.Version, version.Get().Version); err != nil {
		return err
	}

	if err := applyTerraformVersionFlagIfSet(meta.Flavor, terraformProviderVersion); err != nil {
		return err
	}

	result, err := reconcile(mem, afero.NewOsFs(), meta.Flavor != core.FlavorUpjet)
	if err != nil {
		return fmt.Errorf("reconciling generated files: %w\n%s", err, revertAdvice(result.seeded))
	}

	tracked, err := trackedFiles(ctx)
	if err != nil {
		return fmt.Errorf("listing tracked files: %w\n%s", err, revertAdvice(result.seeded))
	}
	result.removed, err = removeOrphans(tracked, mem, afero.NewOsFs())
	if err != nil {
		return fmt.Errorf("removing files this generator no longer produces: %w\n%s", err, revertAdvice(result.seeded))
	}
	result.print(os.Stdout, meta.Version, version.Get().Version)

	if err := applyDependencies(ctx, meta.Flavor); err != nil {
		return fmt.Errorf("%w\n%s", err, revertAdvice(result.seeded))
	}

	fmt.Println("Finalizing...")
	if err := automation.UpdateFinalizePipelineFor(meta.Flavor).Run(); err != nil {
		return fmt.Errorf("%w\n%s", err, revertAdvice(result.seeded))
	}

	if err := stampProvenance(st); err != nil {
		return fmt.Errorf("stamping provenance: %w\n%s", err, revertAdvice(result.seeded))
	}

	fmt.Println("\nUpdate complete. Review the changes with 'git diff' and commit when ready.")
	return nil
}

// revertAdvice tells the user exactly how to undo a failed update. 'git reset
// --hard' alone is not enough once reconcile has run: it seeds new files,
// which git tracks as untracked, so it restores every modified tool-owned
// file but leaves every seeded one behind while the tree looks clean. Naming
// the seeded paths is safer than blanket-advising 'git clean -fd', which would
// also delete any unrelated untracked work already sitting in the repo.
func revertAdvice(seeded []string) string {
	if len(seeded) == 0 {
		return "  changes are uncommitted; run 'git reset --hard' to revert"
	}
	var b strings.Builder
	b.WriteString("  run 'git reset --hard' to revert modified files, then remove the file(s) " +
		"this run seeded (they are untracked, so 'git reset --hard' alone leaves them behind):\n")
	for _, s := range seeded {
		fmt.Fprintf(&b, "    rm -rf %s\n", s)
	}
	return strings.TrimRight(b.String(), "\n")
}

// validateProject loads this plugin's block and re-checks the values PROJECT feeds
// into template paths and generated import paths. `init` and `create api` validate
// them on the way in, but `update` reads a file that may have been edited (or
// arrived in a pull request) since, so it applies the same gate — the flavor's
// own validator, as `create api` uses — before rendering anything.
func validateProject(cfg config.Config) (projectMeta, error) {
	meta, err := loadProjectMeta(cfg)
	if err != nil {
		return projectMeta{}, projectNotUsable(err)
	}
	v := validation.ValidatorFor(meta.Flavor)
	if err := v.ValidateRepository(cfg.GetRepository()); err != nil {
		return projectMeta{}, projectNotUsable(err)
	}
	if domain := cfg.GetDomain(); domain != "" {
		if err := v.ValidateDomain(domain); err != nil {
			return projectMeta{}, projectNotUsable(err)
		}
	}
	resources, err := cfg.GetResources()
	if err != nil {
		return projectMeta{}, fmt.Errorf("reading project resources: %w", err)
	}
	for i := range resources {
		if err := v.ValidateResource(&resources[i]); err != nil {
			return projectMeta{}, projectNotUsable(err)
		}
	}
	return meta, nil
}

// projectNotUsable wraps err with the message validateProject's callers use to report
// that PROJECT failed one of its checks.
func projectNotUsable(err error) error {
	return fmt.Errorf("PROJECT is not usable: %w", err)
}

// loadProjectStore loads the PROJECT config store from the working directory.
func loadProjectStore() (store.Store, error) {
	st := yaml.New(machinery.Filesystem{FS: afero.NewOsFs()})
	if err := st.Load(); err != nil {
		return nil, fmt.Errorf("not a provider project (cannot load PROJECT): %w", err)
	}
	return st, nil
}

// requireCleanTree aborts unless the working tree has no uncommitted changes, so
// the update is reviewable as a diff and no user edits are silently overwritten.
func requireCleanTree(ctx context.Context) error {
	out, err := core.NewCommandRunner("").RunWithOutput(ctx, "git", "status", "--porcelain")
	if err != nil {
		return fmt.Errorf("checking working tree (is this a git repository?): %w", err)
	}
	if strings.TrimSpace(out) != "" {
		return fmt.Errorf("working tree is not clean; commit or stash your changes first so " +
			"the update can be reviewed as a diff")
	}
	return nil
}

// renderToMemFS renders the full template set (init + static + core generators,
// plus each resource's API templates) of the project's flavor into the in-memory
// filesystem. An upjet project renders with the settings PROJECT keeps; its
// user-owned templates need more, which is why reconcile never seeds them.
func renderToMemFS(cfg config.Config, meta projectMeta, memFS machinery.Filesystem) error {
	factory := engine.NewFactoryForFlavor(cfg, meta.Flavor)

	resources, err := cfg.GetResources()
	if err != nil {
		return fmt.Errorf("reading project resources: %w", err)
	}

	initTemplates, err := factory.GetInitTemplates(engine.WithUpjet(meta.Upjet))
	if err != nil {
		return fmt.Errorf("getting init templates: %w", err)
	}

	base := machinery.NewScaffold(memFS,
		machinery.WithConfig(cfg),
		machinery.WithBoilerplate(engine.DefaultBoilerplate()),
	)
	builders := engine.AsBuilders(initTemplates)
	builders = append(builders, engine.CoreGeneratorsFor(meta.Flavor, cfg, resources)...)
	if err := base.Execute(builders...); err != nil {
		return fmt.Errorf("rendering base templates: %w", err)
	}

	for _, res := range resources {
		apiTemplates, err := factory.GetAPITemplates(
			engine.WithForce(true), engine.WithResource(&res), engine.WithUpjet(meta.Upjet))
		if err != nil {
			return fmt.Errorf("getting api templates for %s: %w", res.Kind, err)
		}
		apiScaffold := machinery.NewScaffold(memFS,
			machinery.WithConfig(cfg),
			machinery.WithBoilerplate(engine.DefaultBoilerplate()),
			machinery.WithResource(&res),
		)
		if err := apiScaffold.Execute(engine.AsBuilders(apiTemplates)...); err != nil {
			return fmt.Errorf("rendering api templates for %s: %w", res.Kind, err)
		}
	}
	return nil
}

// applyDependencies bumps the flavor's framework dependency versions from the
// manifest via `go get`, leaving the rest of go.mod (the user's own requires) alone.
func applyDependencies(ctx context.Context, flavor core.Flavor) error {
	deps := engine.DependenciesFor(flavor)
	fmt.Printf("Applying %d framework dependency version(s)...\n", len(deps))
	runner := core.NewCommandRunner("")
	for _, d := range deps {
		if err := runner.RunStreaming(ctx, os.Stdout, os.Stderr, "go", "get", d.Module+"@"+d.Version); err != nil {
			return fmt.Errorf("go get %s@%s: %w", d.Module, d.Version, err)
		}
	}
	return nil
}
