/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v2

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/afero"
	"github.com/spf13/cobra"
	"sigs.k8s.io/kubebuilder/v4/pkg/config"
	"sigs.k8s.io/kubebuilder/v4/pkg/config/store"
	"sigs.k8s.io/kubebuilder/v4/pkg/config/store/yaml"
	"sigs.k8s.io/kubebuilder/v4/pkg/machinery"

	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/automation"
	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/core"
	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/templates/engine"
	"github.com/cychiang/xp-provider-gen/pkg/plugins/crossplane/v2/validation"
	"github.com/cychiang/xp-provider-gen/pkg/version"
)

// NewUpdateCommand returns the `update` command, registered on the CLI via
// cli.WithExtraCommands (kubebuilder's plugin interface has no update hook).
func NewUpdateCommand() *cobra.Command {
	var adopt bool
	var terraformProviderVersion string
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Refresh tool-owned core files of an existing provider",
		Long: `Regenerate the tool-owned core of an existing Crossplane provider — registration,
controller wiring (wiring.go), main.go, config, and framework dependency versions —
to the current generator, without touching your business logic.

Tool-owned files carry a "// Code generated by xp-provider-gen. DO NOT EDIT." header
and are overwritten; files without it (external.go, client.go, options.go, *_types.go,
crossplane.yaml) are left alone. go.mod itself is never overwritten — only its framework
dependency versions are bumped via 'go get', so your own requires are preserved.

On an upjet provider it never recreates a missing user-owned file — some need init-time
Terraform settings PROJECT does not keep, so it recreates none — and lists the ones it
skipped instead. Plain 'update' does not change the wrapped Terraform provider's version;
that lives in your Makefile — use --terraform-provider-version to bump it.

The working tree must be clean; the result is left uncommitted so you can review it with
'git diff' before committing. If a step fails midway, the error names exactly how to revert.

Use --adopt once on a provider generated before the ownership contract existed: it stamps
provenance and writes the header onto recognized tool-owned files so plain 'update' works.

Use --terraform-provider-version on an upjet provider to bump the wrapped Terraform
provider: it rewrites the version in your Makefile, then runs the rest of update as usual —
there is no way to bump only the version, since the generator refresh and framework
dependency bump ride along in the same diff.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			if adopt {
				if err := runAdopt(context.Background()); err != nil {
					return fmt.Errorf("%w\n%s", err, revertAdvice(nil))
				}
				return nil
			}
			if terraformProviderVersion != "" {
				if err := checkTerraformVersionFlag(terraformProviderVersion); err != nil {
					return err
				}
			}
			return runUpdate(context.Background(), terraformProviderVersion)
		},
	}
	cmd.Flags().BoolVar(&adopt, "adopt", false,
		"retrofit an existing provider: stamp provenance and add the generated header to "+
			"tool-owned files, then exit (run 'update' afterward to refresh them)")
	cmd.Flags().StringVar(&terraformProviderVersion, "terraform-provider-version", "",
		"bump the wrapped Terraform provider to this version (upjet only): rewrites the Makefile, "+
			"then runs the rest of update as usual, including a fresh 'make generate'")
	cmd.MarkFlagsMutuallyExclusive("adopt", "terraform-provider-version")
	return cmd
}

// terraformVersionEnvVars are the Makefile's `?=`-assigned variables that would
// make --terraform-provider-version silently no-op if inherited from the
// environment: `?=` only assigns when the variable is unset, so an existing
// value in the environment would win over the flag's Makefile edit without
// any warning.
var terraformVersionEnvVars = []string{"TERRAFORM_PROVIDER_VERSION", "TERRAFORM_NATIVE_PROVIDER_BINARY"}

// checkTerraformVersionFlag rejects a --terraform-provider-version value
// before prepare touches git or the filesystem: either it is not a
// syntactically safe semver value, or an inherited environment variable would
// silently override the Makefile edit this run is about to make.
func checkTerraformVersionFlag(v string) error {
	for _, name := range terraformVersionEnvVars {
		if _, ok := os.LookupEnv(name); ok {
			return fmt.Errorf(
				"rejecting --terraform-provider-version: %s is set in the environment and would "+
					"silently override the Makefile's '?=' assignment; unset it first", name)
		}
	}
	if err := validation.ValidateTerraformProviderVersion(v); err != nil {
		return fmt.Errorf("validating --terraform-provider-version: %w", err)
	}
	return nil
}

// checkTerraformVersionFlavor rejects --terraform-provider-version on a
// non-upjet project: the flag rewrites Makefile lines only an upjet
// project's Makefile.tmpl declares.
func checkTerraformVersionFlavor(flavor core.Flavor) error {
	if flavor != core.FlavorUpjet {
		return fmt.Errorf("rejecting --terraform-provider-version: PROJECT's flavor is %q, not %q",
			flavor, core.FlavorUpjet)
	}
	return nil
}

// prepare enforces the clean-tree precondition, loads and validates the project, and
// renders the current template set of its flavor into an in-memory FS. Both update
// and adopt start here; it also returns the project's plugin block so later steps
// choose the same flavor's sets.
func prepare(ctx context.Context) (store.Store, afero.Fs, projectMeta, error) {
	if err := requireCleanTree(ctx); err != nil {
		return nil, nil, projectMeta{}, err
	}
	st, err := loadProjectStore()
	if err != nil {
		return nil, nil, projectMeta{}, err
	}
	meta, err := validateProject(st.Config())
	if err != nil {
		return nil, nil, projectMeta{}, err
	}
	mem := afero.NewMemMapFs()
	if err := renderToMemFS(st.Config(), meta, machinery.Filesystem{FS: mem}); err != nil {
		return nil, nil, projectMeta{}, fmt.Errorf("rendering tool-owned files: %w", err)
	}
	return st, mem, meta, nil
}

func runAdopt(ctx context.Context) error {
	st, mem, _, err := prepare(ctx)
	if err != nil {
		return err
	}

	adopted, err := adoptHeaders(mem, afero.NewOsFs())
	if err != nil {
		return fmt.Errorf("adopting tool-owned files: %w", err)
	}
	if err := stampProvenance(st); err != nil {
		return fmt.Errorf("stamping provenance: %w", err)
	}

	fmt.Printf("Adopted %d tool-owned file(s) and stamped generator version %s in PROJECT.\n",
		len(adopted), version.Get().Version)
	fmt.Printf("Review with 'git diff', commit, then run '%s update' to refresh them.\n", version.CommandName)
	return nil
}

// adoptHeaders adds the generated header to on-disk files that the templates own
// (identified by the header in their rendered output) but that predate the
// ownership contract. User-owned files are left untouched.
func adoptHeaders(src, dst afero.Fs) ([]string, error) {
	var adopted []string
	err := afero.Walk(src, ".", func(path string, info fs.FileInfo, walkErr error) error {
		if walkErr != nil || info.IsDir() {
			return walkErr
		}
		rel, ok, err := adoptFile(src, dst, path)
		if err != nil {
			return err
		}
		if ok {
			adopted = append(adopted, rel)
		}
		return nil
	})
	return adopted, err
}

// adoptFile adds the header to one on-disk file if the matching rendered file
// is tool-owned and the on-disk file exists without it. Returns whether it
// adopted. This must run for every tool-owned file, Go or not: a headerless
// pre-contract copy that adopt skipped would be classified user-owned by
// core.IsToolOwned and never refreshed by any later plain `update` either.
func adoptFile(src, dst afero.Fs, srcPath string) (string, bool, error) {
	rendered, err := afero.ReadFile(src, srcPath)
	if err != nil {
		return "", false, err
	}
	if !core.IsToolOwned(rendered) {
		return "", false, nil // user-owned template — never adopt
	}
	rel := strings.TrimPrefix(filepath.ToSlash(srcPath), "/")
	if err := checkContained(rel); err != nil {
		return "", false, err
	}
	exists, err := afero.Exists(dst, rel)
	if err != nil {
		return "", false, err
	}
	if !exists {
		return "", false, nil // absent on disk — a later `update` will seed it
	}
	existing, err := afero.ReadFile(dst, rel)
	if err != nil {
		return "", false, err
	}
	if core.IsToolOwned(existing) {
		return "", false, nil // already carries the header
	}
	if err := afero.WriteFile(dst, rel, insertGeneratedHeader(existing), core.FileMode(rel)); err != nil {
		return "", false, err
	}
	return rel, true, nil
}

// insertGeneratedHeader places the header just before the package clause, where
// IsToolOwned looks. It is a no-op if the header is already present. Content
// starting with a shebang gets the header after that first line instead —
// prepending it at byte 0 would break the interpreter line.
func insertGeneratedHeader(content []byte) []byte {
	if core.IsToolOwned(content) {
		return content
	}
	s := string(content)
	if strings.HasPrefix(s, "#!") {
		if nl := strings.IndexByte(s, '\n'); nl >= 0 {
			return []byte(s[:nl+1] + "# " + core.GeneratedHeader + "\n" + s[nl+1:])
		}
	}
	header := core.GeneratedHeader + "\n\n"
	if i := strings.Index(s, "\npackage "); i >= 0 {
		return []byte(s[:i+1] + header + s[i+1:])
	}
	return []byte(header + s)
}

// stampProvenance records the current generator version in PROJECT and saves it.
func stampProvenance(st store.Store) error {
	if err := saveProjectMeta(st.Config(), func(m *projectMeta) {
		m.Version = version.Get().Version
	}); err != nil {
		return fmt.Errorf("encoding provenance: %w", err)
	}
	return st.Save()
}

func runUpdate(ctx context.Context, terraformProviderVersion string) error {
	st, mem, meta, err := prepare(ctx)
	if err != nil {
		return fmt.Errorf("%w\n  no changes were made; nothing to revert", err)
	}

	if terraformProviderVersion != "" {
		if err := checkTerraformVersionFlavor(meta.Flavor); err != nil {
			return fmt.Errorf("%w\n  no changes were made; nothing to revert", err)
		}
		oldVersion, err := applyTerraformVersionBump(afero.NewOsFs(), terraformProviderVersion)
		if err != nil {
			if errors.Is(err, errMakefileWriteFailed) {
				// The write itself failed: afero.WriteFile truncates before
				// writing, so the Makefile on disk may already differ from
				// what git has committed. "no changes were made" would be
				// false here; reconcile has not run yet, so a plain 'git
				// reset --hard' (revertAdvice's no-seeded-files case) is
				// enough to restore it.
				return fmt.Errorf("%w\n%s", err, revertAdvice(nil))
			}
			return fmt.Errorf("%w\n  no changes were made; nothing to revert", err)
		}
		fmt.Printf("Bumped Terraform provider version %s -> %s in Makefile.\n", oldVersion, terraformProviderVersion)
	}

	result, err := reconcile(mem, afero.NewOsFs(), meta.Flavor != core.FlavorUpjet)
	if err != nil {
		return fmt.Errorf("reconciling generated files: %w\n%s", err, revertAdvice(result.seeded))
	}

	tracked, err := trackedFiles(ctx)
	if err != nil {
		return fmt.Errorf("listing tracked files: %w\n%s", err, revertAdvice(result.seeded))
	}
	result.removed, err = removeOrphans(tracked, mem, afero.NewOsFs())
	if err != nil {
		return fmt.Errorf("removing files this generator no longer produces: %w\n%s", err, revertAdvice(result.seeded))
	}
	result.print(os.Stdout, meta.Version)

	if err := applyDependencies(ctx, meta.Flavor); err != nil {
		return fmt.Errorf("%w\n%s", err, revertAdvice(result.seeded))
	}

	fmt.Println("Finalizing...")
	if err := automation.UpdateFinalizePipelineFor(meta.Flavor).Run(); err != nil {
		return fmt.Errorf("%w\n%s", err, revertAdvice(result.seeded))
	}

	if err := stampProvenance(st); err != nil {
		return fmt.Errorf("stamping provenance: %w\n%s", err, revertAdvice(result.seeded))
	}

	fmt.Println("\nUpdate complete. Review the changes with 'git diff' and commit when ready.")
	return nil
}

// revertAdvice tells the user exactly how to undo a failed update. 'git reset
// --hard' alone is not enough once reconcile has run: it seeds new files,
// which git tracks as untracked, so it restores every modified tool-owned
// file but leaves every seeded one behind while the tree looks clean. Naming
// the seeded paths is safer than blanket-advising 'git clean -fd', which would
// also delete any unrelated untracked work already sitting in the repo.
func revertAdvice(seeded []string) string {
	if len(seeded) == 0 {
		return "  changes are uncommitted; run 'git reset --hard' to revert"
	}
	var b strings.Builder
	b.WriteString("  run 'git reset --hard' to revert modified files, then remove the file(s) " +
		"this run seeded (they are untracked, so 'git reset --hard' alone leaves them behind):\n")
	for _, s := range seeded {
		fmt.Fprintf(&b, "    rm -rf %s\n", s)
	}
	return strings.TrimRight(b.String(), "\n")
}

// validateProject loads this plugin's block and re-checks the values PROJECT feeds
// into template paths and generated import paths. `init` and `create api` validate
// them on the way in, but `update` reads a file that may have been edited (or
// arrived in a pull request) since, so it applies the same gate — the flavor's
// own validator, as `create api` uses — before rendering anything.
func validateProject(cfg config.Config) (projectMeta, error) {
	meta, err := loadProjectMeta(cfg)
	if err != nil {
		return projectMeta{}, projectNotUsable(err)
	}
	v := validation.ValidatorFor(meta.Flavor)
	if err := v.ValidateRepository(cfg.GetRepository()); err != nil {
		return projectMeta{}, projectNotUsable(err)
	}
	if domain := cfg.GetDomain(); domain != "" {
		if err := v.ValidateDomain(domain); err != nil {
			return projectMeta{}, projectNotUsable(err)
		}
	}
	resources, err := cfg.GetResources()
	if err != nil {
		return projectMeta{}, fmt.Errorf("reading project resources: %w", err)
	}
	for i := range resources {
		if err := v.ValidateResource(&resources[i]); err != nil {
			return projectMeta{}, projectNotUsable(err)
		}
	}
	return meta, nil
}

// projectNotUsable wraps err with the message validateProject's callers use to report
// that PROJECT failed one of its checks.
func projectNotUsable(err error) error {
	return fmt.Errorf("PROJECT is not usable: %w", err)
}

// loadProjectStore loads the PROJECT config store from the working directory.
func loadProjectStore() (store.Store, error) {
	st := yaml.New(machinery.Filesystem{FS: afero.NewOsFs()})
	if err := st.Load(); err != nil {
		return nil, fmt.Errorf("not a provider project (cannot load PROJECT): %w", err)
	}
	return st, nil
}

// requireCleanTree aborts unless the working tree has no uncommitted changes, so
// the update is reviewable as a diff and no user edits are silently overwritten.
func requireCleanTree(ctx context.Context) error {
	out, err := core.NewCommandRunner("").RunWithOutput(ctx, "git", "status", "--porcelain")
	if err != nil {
		return fmt.Errorf("checking working tree (is this a git repository?): %w", err)
	}
	if strings.TrimSpace(out) != "" {
		return fmt.Errorf("working tree is not clean; commit or stash your changes first so " +
			"the update can be reviewed as a diff")
	}
	return nil
}

// renderToMemFS renders the full template set (init + static + core generators,
// plus each resource's API templates) of the project's flavor into the in-memory
// filesystem. An upjet project renders with the settings PROJECT keeps; its
// user-owned templates need more, which is why reconcile never seeds them.
func renderToMemFS(cfg config.Config, meta projectMeta, memFS machinery.Filesystem) error {
	factory := engine.NewFactoryForFlavor(cfg, meta.Flavor)

	resources, err := cfg.GetResources()
	if err != nil {
		return fmt.Errorf("reading project resources: %w", err)
	}

	initTemplates, err := factory.GetInitTemplates(engine.WithUpjet(meta.Upjet))
	if err != nil {
		return fmt.Errorf("getting init templates: %w", err)
	}

	base := machinery.NewScaffold(memFS,
		machinery.WithConfig(cfg),
		machinery.WithBoilerplate(engine.DefaultBoilerplate()),
	)
	builders := engine.AsBuilders(initTemplates)
	builders = append(builders, engine.CoreGeneratorsFor(meta.Flavor, cfg, resources)...)
	if err := base.Execute(builders...); err != nil {
		return fmt.Errorf("rendering base templates: %w", err)
	}

	for _, res := range resources {
		apiTemplates, err := factory.GetAPITemplates(
			engine.WithForce(true), engine.WithResource(&res), engine.WithUpjet(meta.Upjet))
		if err != nil {
			return fmt.Errorf("getting api templates for %s: %w", res.Kind, err)
		}
		apiScaffold := machinery.NewScaffold(memFS,
			machinery.WithConfig(cfg),
			machinery.WithBoilerplate(engine.DefaultBoilerplate()),
			machinery.WithResource(&res),
		)
		if err := apiScaffold.Execute(engine.AsBuilders(apiTemplates)...); err != nil {
			return fmt.Errorf("rendering api templates for %s: %w", res.Kind, err)
		}
	}
	return nil
}

// reconcile copies every rendered file from src onto dst through the ownership
// gate: tool-owned (headered) files are overwritten, new files seeded, and
// user-owned (headerless) files left untouched. seedUserOwned says whether a
// user-owned file missing on disk is seeded or only recorded as unseeded.
func reconcile(src, dst afero.Fs, seedUserOwned bool) (reconcileResult, error) {
	var result reconcileResult
	err := afero.Walk(src, ".", func(path string, info fs.FileInfo, walkErr error) error {
		if walkErr != nil || info.IsDir() {
			return walkErr
		}
		rel := strings.TrimPrefix(filepath.ToSlash(path), "/")
		decision, err := applyFile(src, dst, path, rel, seedUserOwned)
		if err != nil {
			return err
		}
		result.record(decision, rel)
		return nil
	})
	return result, err
}

// trackedFiles lists the files git tracks in the project, the only files a
// deletion may consider: a file git does not track cannot be restored with
// 'git reset --hard', and `git status --porcelain` — the clean-tree gate — does
// not see ignored files at all, so a disk walk could silently and irreversibly
// delete a headered file sitting in .work/, _output/ or vendor/.
func trackedFiles(ctx context.Context) ([]string, error) {
	out, err := core.NewCommandRunner("").RunWithOutput(ctx, "git", "ls-files", "-z")
	if err != nil {
		return nil, fmt.Errorf("listing git-tracked files: %w", err)
	}
	var files []string
	for _, f := range strings.Split(strings.TrimRight(out, "\x00"), "\x00") {
		if f != "" {
			files = append(files, f)
		}
	}
	return files, nil
}

// removeOrphans deletes the tracked files that carry the generated header but
// are absent from this render: the tool-owned files this generator no longer
// produces. It returns the paths it removed, in the order given.
func removeOrphans(tracked []string, src, dst afero.Fs) ([]string, error) {
	var removed []string
	for _, rel := range tracked {
		if err := checkContained(rel); err != nil {
			return removed, err
		}
		fi, err := dst.Stat(rel)
		switch {
		case os.IsNotExist(err):
			continue // tracked but not on disk — the user already removed it
		case err != nil:
			return removed, err
		case fi.IsDir():
			// A submodule gitlink: git ls-files reports it, but it is not a
			// regular file to read or remove.
			continue
		}
		existing, err := afero.ReadFile(dst, rel)
		if err != nil {
			return removed, err
		}
		if !core.IsToolOwned(existing) {
			continue // user-owned — never touched
		}
		stillRendered, err := afero.Exists(src, rel)
		if err != nil {
			return removed, err
		}
		if stillRendered {
			continue // this run still produces it
		}
		if err := dst.Remove(rel); err != nil {
			return removed, err
		}
		removed = append(removed, rel)
	}
	return removed, nil
}

// checkContained rejects a rendered path that would write outside the project
// directory. Rendered paths come from PROJECT (group/version/kind are
// substituted into template paths), so a hand-edited PROJECT must not be able
// to turn `update` into an arbitrary-file-write primitive.
//
// filepath.IsLocal is the whole check: it rejects absolute paths, any path that
// climbs out of the working directory, and the empty path — using the host's
// own separator rules. Hand-rolling it as a "../" prefix test missed
// backslash-separated escapes on Windows, which is a release target.
func checkContained(rel string) error {
	if !filepath.IsLocal(rel) {
		return fmt.Errorf("refusing to write outside the project: %q", rel)
	}
	return nil
}

// applyFile reconciles one rendered file onto dst per the ownership gate. It
// returns Unseeded when the file is missing on disk, user-owned, and
// seedUserOwned is false: nothing is written.
func applyFile(src, dst afero.Fs, srcPath, rel string, seedUserOwned bool) (core.WriteDecision, error) {
	if err := checkContained(rel); err != nil {
		return core.Skip, err
	}
	exists, err := afero.Exists(dst, rel)
	if err != nil {
		return core.Skip, err
	}
	var existing []byte
	if exists {
		if existing, err = afero.ReadFile(dst, rel); err != nil {
			return core.Skip, err
		}
	}

	decision := core.DecideWrite(exists, existing)
	if decision == core.Skip {
		return decision, nil
	}

	newContent, err := afero.ReadFile(src, srcPath)
	if err != nil {
		return decision, err
	}
	if !exists && !seedUserOwned && !core.IsToolOwned(newContent) {
		return core.Unseeded, nil
	}
	if err := dst.MkdirAll(filepath.Dir(rel), 0o755); err != nil {
		return decision, err
	}
	// Scripts are exec'd directly (uptest runs test/setup.sh), so the write
	// layer owns the executable bit — seeded .sh files must not land 0644.
	return decision, afero.WriteFile(dst, rel, newContent, core.FileMode(rel))
}

type reconcileResult struct {
	overwritten []string
	seeded      []string
	skipped     []string
	// unseeded are user-owned files missing on disk that were deliberately not
	// seeded (upjet: some need init-time Terraform settings PROJECT lacks, so
	// none are recreated).
	unseeded []string
	// removed are tracked, tool-owned files this render no longer produces,
	// deleted by removeOrphans.
	removed []string
}

func (r *reconcileResult) record(decision core.WriteDecision, rel string) {
	switch decision {
	case core.Skip:
		r.skipped = append(r.skipped, rel)
	case core.Seed:
		r.seeded = append(r.seeded, rel)
	case core.Overwrite:
		r.overwritten = append(r.overwritten, rel)
	case core.Unseeded:
		r.unseeded = append(r.unseeded, rel)
	}
}

// print writes the update summary to w. lastVersion is the generator version
// PROJECT was stamped with before this run (empty for a project predating
// provenance stamping); when a removal happened and it differs from the
// version running now, an extra note flags that the removal may be explained
// by an older binary rather than a template this generator truly retired.
func (r reconcileResult) print(w io.Writer, lastVersion string) {
	fmt.Fprintf(w, "Refreshed %d tool-owned file(s), added %d, removed %d, left %d user-owned file(s) untouched.\n",
		len(r.overwritten), len(r.seeded), len(r.removed), len(r.skipped))
	for _, rel := range r.removed {
		fmt.Fprintf(w, "  removed %s: carries the generated header but is no longer generated — "+
			"if this file is yours, remove the header\n", rel)
	}
	if len(r.unseeded) > 0 {
		fmt.Fprintf(w, "Not seeded (user-owned; update does not recreate these on an upjet provider): %s\n",
			strings.Join(r.unseeded, ", "))
	}
	if len(r.removed) > 0 && lastVersion != "" && lastVersion != version.Get().Version {
		fmt.Fprintf(w, "  note: PROJECT was last updated by generator %s; this is %s. "+
			"A removal you did not expect may mean this binary is older.\n",
			lastVersion, version.Get().Version)
	}
}

// terraformProviderVersionLineRe matches the single line a scaffolded upjet
// Makefile declares the wrapped Terraform provider's version on.
var terraformProviderVersionLineRe = regexp.MustCompile(`(?m)^export TERRAFORM_PROVIDER_VERSION \?= (\S+)$`)

// terraformNativeProviderBinaryLineRe matches the single line a scaffolded
// upjet Makefile declares the native provider binary name on, capturing its
// value so the `_v<version>_` substring is only ever replaced inside that
// line, never anywhere else in the file a version string happens to match.
var terraformNativeProviderBinaryLineRe = regexp.MustCompile(`(?m)^export TERRAFORM_NATIVE_PROVIDER_BINARY \?= (.*)$`)

// bumpTerraformVersion rewrites a scaffolded upjet Makefile's two
// version-carrying lines to newVersion: the single
// `export TERRAFORM_PROVIDER_VERSION ?=` line, and the `_v<old>_` substring
// of the TERRAFORM_NATIVE_PROVIDER_BINARY line — and only inside that line's
// value, so a version string that happens to appear elsewhere in the
// Makefile (a comment, a user target) is never touched. It returns the
// rewritten content and the version it replaced.
//
// The Makefile is user-owned, so this only ever changes the value already
// declared there — it never assumes a binary-name suffix (`_x5`) or provider
// name beyond that substring. It requires exactly one line of each kind, and
// requires the binary line to already carry that same old version: a
// Makefile that fails either check already disagrees with itself about the
// current version, and guessing which line is right would be worse than
// refusing.
func bumpTerraformVersion(makefile []byte, newVersion string) ([]byte, string, error) {
	versionMatches := terraformProviderVersionLineRe.FindAllSubmatch(makefile, -1)
	if len(versionMatches) != 1 {
		return nil, "", fmt.Errorf(
			"finding a single 'export TERRAFORM_PROVIDER_VERSION ?=' line in Makefile (found %d)", len(versionMatches))
	}
	oldVersion := string(versionMatches[0][1])

	binaryMatches := terraformNativeProviderBinaryLineRe.FindAllSubmatch(makefile, -1)
	if len(binaryMatches) != 1 {
		return nil, "", fmt.Errorf(
			"finding a single 'export TERRAFORM_NATIVE_PROVIDER_BINARY ?=' line in Makefile (found %d)", len(binaryMatches))
	}
	oldMarker := []byte("_v" + oldVersion + "_")
	if !bytes.Contains(binaryMatches[0][1], oldMarker) {
		return nil, "", fmt.Errorf(
			"finding %q in Makefile's TERRAFORM_NATIVE_PROVIDER_BINARY line", oldMarker)
	}
	newMarker := []byte("_v" + newVersion + "_")

	updated := terraformProviderVersionLineRe.ReplaceAllFunc(makefile, func([]byte) []byte {
		return []byte("export TERRAFORM_PROVIDER_VERSION ?= " + newVersion)
	})
	updated = terraformNativeProviderBinaryLineRe.ReplaceAllFunc(updated, func(line []byte) []byte {
		return bytes.Replace(line, oldMarker, newMarker, 1)
	})
	return updated, oldVersion, nil
}

// applyTerraformVersionBump reads the project's Makefile from dst, rewrites it
// via bumpTerraformVersion, and writes the result back, returning the version
// it replaced. It must run after prepare, never before: rewriting the
// Makefile ahead of requireCleanTree would make the flag reject itself on
// every run, since the tree requireCleanTree then sees is no longer clean.
func applyTerraformVersionBump(dst afero.Fs, newVersion string) (string, error) {
	const makefilePath = "Makefile"
	content, err := afero.ReadFile(dst, makefilePath)
	if err != nil {
		return "", fmt.Errorf("reading Makefile: %w", err)
	}
	updated, oldVersion, err := bumpTerraformVersion(content, newVersion)
	if err != nil {
		return "", fmt.Errorf("bumping Terraform provider version in Makefile: %w", err)
	}
	if err := afero.WriteFile(dst, makefilePath, updated, core.FileMode(makefilePath)); err != nil {
		return "", fmt.Errorf("%w: %w", errMakefileWriteFailed, err)
	}
	return oldVersion, nil
}

// errMakefileWriteFailed marks an applyTerraformVersionBump failure that
// happened during the write itself, once afero.WriteFile's O_TRUNC may
// already have truncated the file on disk. Unlike the read/parse failures
// above it, "no changes were made" would be false here — the tree is left
// dirty, and only a plain 'git reset --hard' (revertAdvice's no-seeded-files
// case, correct here since reconcile has not run yet) restores it.
var errMakefileWriteFailed = errors.New("writing Makefile")

// applyDependencies bumps the flavor's framework dependency versions from the
// manifest via `go get`, leaving the rest of go.mod (the user's own requires) alone.
func applyDependencies(ctx context.Context, flavor core.Flavor) error {
	deps := engine.DependenciesFor(flavor)
	fmt.Printf("Applying %d framework dependency version(s)...\n", len(deps))
	runner := core.NewCommandRunner("")
	for _, d := range deps {
		if err := runner.RunStreaming(ctx, os.Stdout, os.Stderr, "go", "get", d.Module+"@"+d.Version); err != nil {
			return fmt.Errorf("go get %s@%s: %w", d.Module, d.Version, err)
		}
	}
	return nil
}
