# Shared helpers for scripts/e2e-native.sh, scripts/e2e-upjet.sh and
# scripts/e2e-upgrade.sh. Source it, do not execute it.

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

# fail prints an error and exits — the common "assert or bail" idiom used
# throughout these scripts.
fail() { log_error "✗ $1"; exit 1; }

# section_header prints a banner with the given title — the one definition of
# the banner format, for non-step sections such as a summary or cleanup.
section_header() {
    echo -e "\n${BLUE}========================================${NC}"
    echo -e "${BLUE} $1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

# step_header prints a banner for numbered step N with the given title —
# the shared step-output format for all three e2e scripts.
step_header() { section_header "Step $1: $2"; }

# E2E_SKIP_DOCKER is a real boolean, not a "set means yes" flag: unset, empty,
# 0/false/no means "do not skip"; anything else (1, true, yes, ...) means
# "skip". Centralized here so the truthiness test isn't repeated (and doesn't
# drift) across every call site.
docker_skip_requested() {
    case "${E2E_SKIP_DOCKER:-0}" in
        0 | false | False | FALSE | no | No | NO) return 1 ;;
        *) return 0 ;;
    esac
}

# assert_force_refreshes <tool_file> <user_file> -- <command...>
#
# Marks <tool_file> (tool-owned) and <user_file> (user-owned) with distinct
# markers and commits, runs <command...> (expected: `create api --force`),
# then asserts the tool-owned marker was regenerated away and the
# user-owned marker survived. Repeats <command...> a second time and
# asserts that no-op run exits 0, reports the no-change skip, and adds no
# commit (git.go's stageAndCheck skips the commit when nothing is staged).
assert_force_refreshes() {
    local tool_file=$1 user_file=$2
    shift 2
    [[ ${1:-} == "--" ]] && shift

    local tool_marker="// FORCE-MARKER: stale tool-owned content"
    local user_marker="// FORCE-MARKER: user customization"
    printf '\n%s\n' "$tool_marker" >>"$tool_file"
    printf '\n%s\n' "$user_marker" >>"$user_file"
    git add -A && git commit -q -m "simulate: stale tool-owned file and a user customization before --force" ||
        fail "could not commit the simulated --force drift"

    ASSERT_LOG="$(mktemp)"
    if ! "$@" >"$ASSERT_LOG" 2>&1; then
        tail -30 "$ASSERT_LOG"
        rm -f "$ASSERT_LOG"
        fail "create api --force failed"
    fi
    rm -f "$ASSERT_LOG"

    grep -qF "$tool_marker" "$tool_file" && fail "--force did not refresh tool-owned $tool_file (marker survived)"
    grep -qF "$user_marker" "$user_file" || fail "--force clobbered user-owned $user_file (marker gone)"
    log_success "✓ --force refreshed tool-owned $tool_file, preserved user-owned $user_file"

    local head_before
    head_before="$(git rev-parse HEAD)"
    ASSERT_LOG="$(mktemp)"
    if ! "$@" >"$ASSERT_LOG" 2>&1; then
        tail -30 "$ASSERT_LOG"
        rm -f "$ASSERT_LOG"
        fail "second --force (no changes) did not exit 0"
    fi
    grep -q "No changes to commit" "$ASSERT_LOG" || {
        rm -f "$ASSERT_LOG"
        fail "second --force did not report the no-change skip"
    }
    rm -f "$ASSERT_LOG"
    [[ "$(git rev-parse HEAD)" == "$head_before" ]] ||
        fail "second --force added or amended a commit although nothing changed"
    log_success "✓ second --force exited 0 with nothing to commit, added no commit"
}

# assert_adopt_restores <file> -- <command...>
#
# Strips the tool-owned "DO NOT EDIT" header from <file> and commits
# (simulating a provider generated before the ownership contract), then
# runs <command...> (expected: `update --adopt`) and asserts the header was
# restored. On success, leaves the command's combined output in
# $ASSERT_LOG for callers that need to inspect it further; the caller is
# responsible for removing it.
assert_adopt_restores() {
    local file=$1
    shift
    [[ ${1:-} == "--" ]] && shift

    grep -v "Code generated by xp-provider-gen" "$file" >"$file.tmp" && mv "$file.tmp" "$file"
    grep -q "DO NOT EDIT" "$file" && fail "failed to strip the header from $file for the --adopt test"
    git add -A && git commit -q -m "simulate: provider without generated headers" ||
        fail "could not commit the simulated pre-contract state"

    ASSERT_LOG="$(mktemp)"
    if ! "$@" >"$ASSERT_LOG" 2>&1; then
        tail -30 "$ASSERT_LOG"
        rm -f "$ASSERT_LOG"
        fail "update --adopt failed"
    fi
    grep -q "DO NOT EDIT" "$file" || fail "adopt did not restore the header on $file"
    log_success "✓ adopt restored the header on $file"
}

# assert_update_refuses_dirty <binary> <dirty_file>
#
# Dirties <dirty_file>, runs `<binary> update`, asserts it refuses (a
# non-zero exit whose output mentions "working tree" — update.go's
# requireCleanTree, shared by both flavors), then restores the file.
assert_update_refuses_dirty() {
    local binary=$1 file=$2
    printf '\n// dirty\n' >>"$file"
    ASSERT_LOG="$(mktemp)"
    if "$binary" update >"$ASSERT_LOG" 2>&1; then
        cat "$ASSERT_LOG"
        rm -f "$ASSERT_LOG"
        fail "update should have refused a dirty working tree"
    fi
    grep -qi 'working tree' "$ASSERT_LOG" || {
        cat "$ASSERT_LOG"
        rm -f "$ASSERT_LOG"
        fail "update's dirty-tree refusal did not mention the working tree"
    }
    rm -f "$ASSERT_LOG"
    git checkout -- "$file" 2>/dev/null || git restore "$file"
    log_success "✓ update refused a dirty working tree"
}
