/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package core

// Flavor selects which kind of provider a project is, which in turn selects the
// template tree it is scaffolded from. A project's flavor is chosen once at
// `init` and recorded in PROJECT, so later commands never ask again.
type Flavor string

const (
	// FlavorNative is a provider whose reconcile logic the author writes by
	// hand behind the seam contract.
	FlavorNative Flavor = "native"

	// FlavorUpjet is a provider whose types and controllers are generated by
	// upjet from a Terraform provider schema; the author writes configuration.
	FlavorUpjet Flavor = "upjet"
)

// TemplateRoot is the directory in the embedded template FS that holds this
// flavor's scaffold. Each root is self-contained: everything a provider of that
// flavor gets is visible in one directory.
func (f Flavor) TemplateRoot() string {
	if f == FlavorUpjet {
		return "upjet"
	}
	return "files"
}

// Valid reports whether f is a flavor this tool knows how to scaffold.
func (f Flavor) Valid() bool {
	return f == FlavorNative || f == FlavorUpjet
}
