/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package core

import "bytes"

// GeneratedHeader marks a file as tool-owned: regenerated by `xp-provider-gen
// update` and safe to overwrite. Files without it are user-owned and never
// touched once created. It is the standard Go "code generated" form, so tools
// (golangci-lint, etc.) also recognize these files as generated.
const GeneratedHeader = "// Code generated by xp-provider-gen. DO NOT EDIT."

// headerScanLimit bounds how far into a file we look for the header (it always
// appears near the top, after the license boilerplate).
const headerScanLimit = 1024

// IsToolOwned reports whether content carries the generated header, i.e. the
// tool owns the file and may overwrite it.
func IsToolOwned(content []byte) bool {
	head := content
	if len(head) > headerScanLimit {
		head = head[:headerScanLimit]
	}
	return bytes.Contains(head, []byte(GeneratedHeader))
}

// WriteDecision is what an update should do with a single target file.
type WriteDecision int

const (
	// Skip leaves an existing user-owned file untouched.
	Skip WriteDecision = iota
	// Seed writes a file that does not yet exist.
	Seed
	// Overwrite replaces an existing tool-owned file.
	Overwrite
)

// DecideWrite applies the overwrite gate: seed if absent, overwrite if the
// existing file is tool-owned, otherwise skip (never clobber user files).
func DecideWrite(targetExists bool, existingContent []byte) WriteDecision {
	switch {
	case !targetExists:
		return Seed
	case IsToolOwned(existingContent):
		return Overwrite
	default:
		return Skip
	}
}
