apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-workflow
  annotations:
    meta.crossplane.io/maintainer: provider-workflow Maintainers <noreply@crossplane.io>
    meta.crossplane.io/source: github.com/test/provider-workflow
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      provider-workflow is a Crossplane provider for provider-workflow.
    meta.crossplane.io/readme: |
      This `provider-provider-workflow` repository is the Crossplane infrastructure provider for
      provider-workflow. The provider that is built from the source code in this repository can be
      installed into a Crossplane control plane and adds the following new functionality:

      * Custom Resource Definitions (CRDs) that model provider-workflow infrastructure and services
      * Controllers to provision these resources in provider-workflow based on the users desired state captured in CRDs they create
      * Implementations of Crossplane's portable resource abstractions, enabling provider-workflow resources to fulfill a user's general need for cloud services

spec:
  controller:
    image: github.com/test/provider-workflow:latest